shfmt

diff --git a/scripts/cipublish b/scripts/cipublish
--- a/scripts/cipublish
+++ b/scripts/cipublish
@@ -3,29 +3,29 @@
 set -e
 
 if [[ -n "${GFW_IAC_WORKSHOP_DEBUG}" ]]; then
-    set -x
+	set -x
 fi
 
 function usage() {
-    echo -n \
-        "Usage: $(basename "$0")
+	echo -n \
+		"Usage: $(basename "$0")
 Publish container images to Elastic Container Registry (ECR).
 "
 }
 
 if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
-    if [ "${1:-}" = "--help" ]; then
-        usage
-    else
-        if [[ -n "${GFW_IAC_WORKSHOP_AWS_ECR_ENDPOINT}" ]]; then
-            # Evaluate the return value of the get-login subcommand, which
-            # is a docker login command with temporarily ECR credentials.
-            eval "$(aws ecr get-login --no-include-email)"
+	if [ "${1:-}" = "--help" ]; then
+		usage
+	else
+		if [[ -n "${GFW_IAC_WORKSHOP_AWS_ECR_ENDPOINT}" ]]; then
+			# Evaluate the return value of the get-login subcommand, which
+			# is a docker login command with temporarily ECR credentials.
+			eval "$(aws ecr get-login --no-include-email)"
 
-            docker push "${GFW_IAC_WORKSHOP_AWS_ECR_ENDPOINT}/hello-world-rds:latest"
-        else
-            echo "ERROR: No GFW_IAC_WORKSHOP_AWS_ECR_ENDPOINT variable defined."
-            exit 1
-        fi
-    fi
+			docker push "${GFW_IAC_WORKSHOP_AWS_ECR_ENDPOINT}:latest"
+		else
+			echo "ERROR: No GFW_IAC_WORKSHOP_AWS_ECR_ENDPOINT variable defined."
+			exit 1
+		fi
+	fi
 fi
