remove git_commit from infra

diff --git a/scripts/infra b/scripts/infra
--- a/scripts/infra
+++ b/scripts/infra
@@ -13,43 +13,33 @@ Execute Terraform subcommands.
 "
 }
 
-if [[ -n "${GIT_COMMIT}" ]]; then
-    GIT_COMMIT="${GIT_COMMIT:0:7}"
-else
-    GIT_COMMIT="$(git rev-parse --short HEAD)"
-fi
-
 if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
     if [ "${1:-}" = "--help" ]; then
         usage
     else
         TERRAFORM_DIR="$(dirname "$0")/../terraform"
-        echo
-        echo "Attempting to deploy application version [${GIT_COMMIT}]..."
-        echo "-----------------------------------------------------"
-        echo
+
+        pushd "${TERRAFORM_DIR}"
+
+        case "${1}" in
+        plan)
+            # Clear stale modules, then re-initialize
+            rm -rf .terraform terraform.tfstate*
+            terraform init
+
+            terraform plan \
+                -var-file="gfw-iac-workshop.tfvars" \
+                -out="gfw-iac-workshop.tfplan"
+            ;;
+        apply)
+            terraform apply "gfw-iac-workshop.tfplan"
+            ;;
+        *)
+            echo "ERROR: I don't have support for that Terraform subcommand!"
+            exit 1
+            ;;
+        esac
+
+        popd
     fi
-
-    pushd "${TERRAFORM_DIR}"
-
-    case "${1}" in
-    plan)
-        # Clear stale modules, then re-initialize
-        rm -rf .terraform terraform.tfstate*
-        terraform init
-
-        terraform plan \
-            -var-file="gfw-iac-workshop.tfvars" \
-            -out="gfw-iac-workshop.tfplan"
-        ;;
-    apply)
-        terraform apply "gfw-iac-workshop.tfplan"
-        ;;
-    *)
-        echo "ERROR: I don't have support for that Terraform subcommand!"
-        exit 1
-        ;;
-    esac
-
-    popd
 fi
